// [game name, node name in file, file url]
export const Models: [string, string, string][] = [
  ["craftMiner", "craft_miner", "./assets/models/craft_miner_scaled.glb"],
  ["craftMinerHull", "craft_miner", "./assets/models/craft_miner_hull.glb"],
  ["craftSpeederA", "craft_speederA", "./assets/models/craft_speederA_scaled.glb"],
  ["craftSpeederAHull", "craft_speederA", "./assets/models/craft_speederA_hull.glb"],
  ["craftSpeederB", "craft_speederB", "./assets/models/craft_speederB_scaled.glb"],
  ["craftSpeederBHull", "craft_speederB", "./assets/models/craft_speederB_hull.glb"],
  ["craftSpeederC", "craft_speederC", "./assets/models/craft_speederC_scaled.glb"],
  ["craftSpeederCHull", "craft_speederC", "./assets/models/craft_speederC_hull.glb"],
  ["craftSpeederD", "craft_speederD", "./assets/models/craft_speederD_scaled.glb"],
  ["craftSpeederDHull", "craft_speederD", "./assets/models/craft_speederD_hull.glb"],
  ["spaceCraft1", "spaceCraft1", "./assets/models/spaceCraft1.glb"],
  ["spaceCraft1Hull", "spaceCraft1", "./assets/models/spaceCraft1_hull.glb"],
  ["spaceCraft2", "spaceCraft2", "./assets/models/spaceCraft2.glb"],
  ["spaceCraft2Hull", "spaceCraft2", "./assets/models/spaceCraft2_hull.glb"],
  ["spaceCraft3", "spaceCraft3", "./assets/models/spaceCraft3.glb"],
  ["spaceCraft3Hull", "spaceCraft3", "./assets/models/spaceCraft3_hull.glb"],
  ["spaceCraft4", "spaceCraft4", "./assets/models/spaceCraft4.glb"],
  ["spaceCraft4Hull", "spaceCraft4", "./assets/models/spaceCraft4_hull.glb"],
  ["spaceCraft5", "spaceCraft5", "./assets/models/spaceCraft5.glb"],
  ["spaceCraft5Hull", "spaceCraft5", "./assets/models/spaceCraft5_hull.glb"],
  ["meteor", "meteor", "./assets/models/meteor.glb"],
  // ["meteorHalf", "meteor_half", "/assets/meteor_half.glb"],
  // ["meteorDetailed", "meteor_detailed", "/assets/meteor_detailed.glb"],
]